# Site settings
title: Rewon Child 
email: rewonc@gmail.com
description: Rewon Child is a full-stack software engineer and entrepreneur living in San Francisco, California.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rewonc.github.io" # the base hostname & protocol for your site
twitter_username: rewonfc
github_username:  rewonc

# Build settings
markdown: kramdown
